apiVersion: v1
kind: ConfigMap
metadata:
  name: f7t-client-secrets-configmap
  namespace: {{ .Values.global.namespace }}
data:
  client_secrets.json: |
    {
      "web": {
        "client_id": "firecrest-sample",
        "client_secret": "b391e177-fa50-4987-beaf-e6d33ca93571",
        "issuer": "http://localhost:8080/auth/realms/kcrealm",
        "auth_uri": "http://localhost:8080/auth/realms/kcrealm/protocol/openid-connect/auth",
        "redirect_uris": [
              "http://kong:8000/*"
        ],
        "userinfo_uri": "http://svc-keycloak:8080/auth/realms/kcrealm/protocol/openid-connect/userinfo",
        "token_uri": "http://svc-keycloak:8080/auth/realms/kcrealm/protocol/openid-connect/token"
      }
    }
