apiVersion: v1
kind: Service # this is basically a proxy configuration to route connections to pods
metadata:
  name: svc-f7t-client
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: f7t-client # will match pods with this label
  ports:
  - port: 5000 # the service listen on
    targetPort: 5000 # the pods listen on
