apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
      - image: demo_storage
        imagePullPolicy: Never
        name: storage
        ports:
        - containerPort: 5002
        envFrom:
        - configMapRef:
            name: common-env-file
        env:
        - name: F7T_CERT_CIPHER_KEY
          value: Df6UZuoPoJ2u5yRwxNfFQ46Nwy8eW1OGTcuhlqn4ONo=
        - name: F7T_STORAGE_POLLING_INTERVAL
          value: "60"
        - name: F7T_S3_SECRET_KEY
          value: storage_secret_key
        - name: F7T_S3_ACCESS_KEY
          value: storage_access_key
        - name: F7T_S3_URL
          value: http://svc-minio:9000
        volumeMounts:
        - mountPath: /var/log
          name: logs-endpoint
        - mountPath: /user-key
          subPath: user-key
          name: user-key-public
      volumes:
      - emptyDir: {}
        name: logs-endpoint
      - name: user-key-public
        configMap:
          name: f7t-user-ssh-keys