apiVersion: v1
data:
  F7T_CERTIFICATOR_PORT: "{{ .Values.F7T_CERTIFICATOR_PORT }}"
  F7T_OPA_URL: "{{ .Values.F7T_OPA_URL }}"
  F7T_OPA_USE: "{{ .Values.F7T_OPA_USE }}"
  F7T_POLICY_PATH: "{{ .Values.F7T_POLICY_PATH }}"
  F7T_CA_KEY_PATH: "{{ .Values.F7T_CA_KEY_PATH }}"
  F7T_PUB_USER_KEY_PATH: "{{ .Values.F7T_PUB_USER_KEY_PATH }}"
kind: ConfigMap
metadata:
  name: certificator-env-file
  namespace: {{ .Values.global.namespace }}
  annotations:
    reloader.stakater.com/match: "true"
