apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: deploy-certificator
    namespace: {{ .Values.global.namespace }}
    {{ if ne .Values.global.environment "dev" }}
    annotations:
      configmap.reloader.stakater.com/reload: "certificator-env-file,common-env-file"
      secret.reloader.stakater.com/reload: "firecrest-ca-key-secret"
    {{ end }}
  spec:
    selector:
      matchLabels:
        app: certificator
    template:
      metadata:
        labels:
          app: certificator
      spec:
        containers:
        - name: f7t-opa
          image: openpolicyagent/opa:0.22.0
          args: ["run", "--server", "--log-level=debug", "--log-format=json-pretty", "--skip-version-check", "/opa-files/data.json", "/opa-files/policy.rego"]
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: {{ .Values.F7T_OPA_PORT | atoi }}
          volumeMounts:
          - mountPath: /opa-files/
            name: f7t-opa-vol
          startupProbe:
            tcpSocket:
              port: {{ .Values.F7T_OPA_PORT | atoi }}
            initialDelaySeconds: 5
            failureThreshold: 1
        - name: f7t-certificator
          image: "{{ .Values.global.registry }}/certificator:{{ .Values.global.tag }}"
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: {{ .Values.F7T_CERTIFICATOR_PORT | atoi }}
          envFrom:
            - configMapRef:
                name: common-env-file
            - configMapRef:
                name: certificator-env-file
          command: ["sh"]
          args: ["-c", "/usr/local/bin/gunicorn --ciphers TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256,TLS_AES_128_GCM_SHA256,DHE-RSA-AES256-GCM-SHA384,ECDHE-RSA-AES256-GCM-SHA384,ECDHE-RSA-AES128-GCM-SHA256 --ssl-version TLSv1_2 --keyfile $F7T_SSL_KEY --certfile $F7T_SSL_CRT --workers=2 --bind :5010 --error-logfile /var/log/certificator.gunicorn.log certificator:app"]
          volumeMounts:
          - mountPath: "{{ .Values.F7T_CA_KEY_PATH }}"
            name: f7t-cert-vol
            subPath: ca-key        
          - mountPath: "{{ .Values.F7T_PUB_USER_KEY_PATH }}"
            name: f7t-cert-user-pub-vol
            subPath: user-key.pub
          - mountPath: /f7t-ssl.crt
            name: f7t-ssl-crt
            subPath: f7t-ssl.crt
          - mountPath: /f7t-ssl.key
            name: f7t-ssl-key
            subPath: f7t-ssl.key
          startupProbe:
            tcpSocket:
              port: {{ .Values.F7T_CERTIFICATOR_PORT | atoi }}
            initialDelaySeconds: 5
            failureThreshold: 1
        volumes:
        - name: f7t-opa-vol
          configMap:
            name: f7t-opa-configmap
        
        - name: f7t-cert-vol
          {{ if eq .Values.global.environment "dev" }}
          configMap:
            name: f7t-ca-ssh-keys
            items:
              - key: ca-key
                path: ca-key
                mode: 0400
          {{ else }}
          secret:
            secretName: firecrest-ca-key-secret
            items:
            - key: F7T_CA_KEY
              path: ca-key            
            defaultMode: 0400
          {{ end }}
        - name: f7t-cert-user-pub-vol
          configMap:
            name: f7t-user-ssh-pub-keys
        - name: f7t-ssl-crt
          configMap:
            name: f7t-ssl-crt
        - name: f7t-ssl-key
          configMap:
            name: f7t-ssl-key
kind: List
