apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: svc-certificator
    namespace: {{ .Values.global.namespace }}
  spec:
    type: ClusterIP
    selector:
      app: certificator
    ports:
    - name: opa
      protocol: TCP
      port: {{ .Values.F7T_OPA_PORT | default 8181 | atoi }}
      targetPort: {{ .Values.F7T_OPA_PORT | default 8181 | atoi }}
    - name: certificator
      protocol: TCP
      port: {{ .Values.F7T_CERTIFICATOR_PORT | default 5000 | atoi }}
      targetPort: {{ .Values.F7T_CERTIFICATOR_PORT | default 5000 | atoi }}
kind: List
