apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: svc-certificator
    namespace: {{ .Values.global.namespace }}
  spec:
    type: ClusterIP
    selector:
      app: certificator
    ports:
    - name: "{{ .Values.F7T_OPA_PORT }}"
      protocol: TCP
      port: {{ .Values.F7T_OPA_PORT | atoi }}
      targetPort: {{ .Values.F7T_OPA_PORT | atoi }}
    - name: "{{ .Values.F7T_CERTIFICATOR_PORT }}"
      protocol: TCP
      port: {{ .Values.F7T_CERTIFICATOR_PORT | atoi }}
      targetPort: {{ .Values.F7T_CERTIFICATOR_PORT | atoi }}
kind: List
