apiVersion: v1
data:
  F7T_AUTH_ALLOWED_USERS: ''''''
  F7T_AUTH_REQUIRED_SCOPE: '''firecrest'''
  F7T_AUTH_ROLE: '''firecrest-sa'''
  F7T_AUTH_TOKEN_AUD: ''''''
  F7T_AUTH_TOKEN_ISSUER: '''http://localhost:8080/auth/realms/kcrealm'''
  F7T_CERTIFICATOR_IP: certificator
  F7T_CERTIFICATOR_PORT: "5010"
  F7T_CERTIFICATOR_URL: http://svc-certificator:5010
  F7T_COMPUTE_BASE_FS: '"/home;/home"'
  F7T_COMPUTE_IP: compute
  F7T_COMPUTE_PORT: "5006"
  F7T_COMPUTE_URL: http://svc-compute:5006
  F7T_EXT_TRANSFER_MACHINE_INTERNAL: '''svc-cluster:22'''
  F7T_EXT_TRANSFER_MACHINE_PUBLIC: '''cluster'''
  F7T_FILESYSTEMS: '"/home"'
  F7T_FIRECREST_SERVICE: '''firecrest.some.place'''
  F7T_KONG_COMPUTE_URL: http://svc-compute:5006
  F7T_KONG_STATUS_URL: http://svc-status:5001
  F7T_KONG_STORAGE_URL: http://svc-storage:5002
  F7T_KONG_TASKS_URL: http://svc-tasks:5003
  F7T_KONG_URL: http://svc-kong:8000
  F7T_KONG_UTILITIES_URL: http://svc-utilities:5004
  F7T_KONG_RESERVATIONS_URL: http://svc-reservations:5005
  F7T_OBJECT_STORAGE: '''s3v4'''
  F7T_OPA_URL: http://localhost:8181
  F7T_OPA_USE: "True"
  F7T_PERSISTENCE_IP: localhost
  F7T_POLICY_PATH: v1/data/f7t/authz
  F7T_REALM_RSA_PUBLIC_KEY: '''MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqB44q32bQp8LbyW6dQvgsjseXESkLT1g5LQKGb+P79AC+nOAtxhn8i/kmgc6zsQH8NlUtNJruLxlzdo2/OGmlDGYZH1x6VmAwvJPJ4er0xPUrvZ8YclxYQC16PY5LFiQRNBMRyQwP5Kne1O46FpmADFVWMfoabdnaqoXexxB56b25o8tE2ulRBgfpnrRgZAvf7kWjugRCNO06FV074FVMYHA1aBk0ICyaFCDM/Tb5oaDyGr5c/ZvdrRUrw8vaiYyMgaAnnJPL75cebGoHeMJaEyZalsHA+iuhRAfeAwpSClsmhVqnfH7a7hqrqumVRo27dydqmfVgpFjU5gbFcBZ5wIDAQAB'''
  F7T_REALM_RSA_TYPE: RS256
  F7T_RESERVATIONS_IP: reservations
  F7T_RESERVATIONS_PORT: "5005"
  F7T_RESERVATIONS_URL: http://svc-reservations:5005
  F7T_SSH_CERTIFICATE_WRAPPER: "True"
  F7T_SPANK_PLUGIN_OPTION: --nohome
  F7T_STATUS_IP: status
  F7T_STATUS_PORT: "5001"
  F7T_STATUS_SERVICES: '''certificator;utilities;compute;tasks;storage'''
  F7T_STATUS_SYSTEMS: '''svc-cluster:22'''
  F7T_STATUS_URL: http://svc-status:5001
  F7T_STORAGE_IP: storage
  F7T_STORAGE_JOBS_MACHINE: cluster
  F7T_STORAGE_MAX_FILE_SIZE: "5120"
  F7T_STORAGE_PORT: "5002"
  F7T_STORAGE_TEMPURL_EXP_TIME: "604800"
  F7T_STORAGE_URL: http://svc-storage:5002
  F7T_SYSTEMS_INTERNAL_COMPUTE: '''svc-cluster:22'''
  F7T_SYSTEMS_INTERNAL_STORAGE: '''svc-cluster:22'''
  F7T_SYSTEMS_INTERNAL_UTILITIES: '''svc-cluster:22'''
  F7T_SYSTEMS_PUBLIC: '''cluster'''
  F7T_TASKS_IP: tasks
  F7T_TASKS_PORT: "5003"
  F7T_TASKS_URL: http://svc-tasks:5003
  F7T_UTILITIES_IP: utilities
  F7T_UTILITIES_MAX_FILE_SIZE: "5"
  F7T_UTILITIES_PORT: "5004"
  F7T_UTILITIES_TIMEOUT: "5"
  F7T_UTILITIES_URL: http://svc-utilities:5004
  F7T_USE_SPANK_PLUGIN: '"True;True"'  
  F7T_XFER_PARTITION: xfer
kind: ConfigMap
metadata:
  name: common-env-file
