apiVersion: v1
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: f7t-opa-configmap
  data:
    data.json: |
      {
        "systems": {
          "cluster": {
            "users": ["test1", "service-account-firecrest-sample"] 
          },
          "not_a_system": {
            "users": ["testuser"]
          }
        }        
      }
    policy.rego: |
      package f7t.authz
      import input
      import data
      default allow = false
      allow {
        some some_user
        data.systems[input.system].users[some_user] == input.user
      }
kind: List
