apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: svc-certificator
  spec:
    type: ClusterIP
    selector:
      app: certificator
    ports:
    - name: "8181"
      protocol: TCP
      port: 8181
      targetPort: 8181
    - name: "5010"
      port: TCP
      port: 5010
      targetPort: 5010
kind: List
