apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-redis
  namespace: {{ .Values.global.namespace }}
  {{ if ne .Values.global.environment "dev" }}
  annotations:
    configmap.reloader.stakater.com/reload: "tasks-env-file,common-env-file"
    secret.reloader.stakater.com/reload: "firecrest-common-secrets"
  {{ end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: taskpersistence
        image: redis:5
        command:
        - /usr/local/bin/redis-server 
        - "/redis/redis.conf"
        - --requirepass 
        - "$(F7T_PERSIST_PWD)"
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "sleep 10"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: {{ .Values.F7T_PERSIST_PORT | atoi }}
        env:
          - name: F7T_PERSIST_PWD
            {{ if eq .Values.global.environment "dev" }}
            value: {{ .Values.F7T_PERSIST_PWD }}
            {{ else }} 
            valueFrom:
              secretKeyRef:
                name: firecrest-common-secrets
                key: F7T_PERSIST_PWD
            {{ end }}
        volumeMounts:
        - mountPath: /var/log
          name: logs-endpoint
        - mountPath: /data
          name: redis-data
        - mountPath: /redis
          name: redis-config
      volumes:
        - name: logs-endpoint
          emptyDir: {}
        - name: redis-data
          {{ if ne .Values.global.environment "dev" }}
          persistentVolumeClaim:
            claimName: firecrest-redis-pvc
          {{ else }}
          emptyDir: {}
          {{ end }}
        - name: redis-config
          configMap:
            name: f7t-redis
      



