apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: svc-cluster
  spec:
    type: ClusterIP
    selector:
      app: cluster
    ports:
    - name: "22"
      protocol: TCP
      port: 22
      targetPort: 22
kind: List
