# certificator
F7T_CERTIFICATOR_PORT: "5010"
F7T_OPA_URL: http://localhost:8181
F7T_OPA_PORT: "8181"
F7T_OPA_ENABLED: "True"
F7T_OPA_POLICY_PATH: v1/data/f7t/authz
F7T_CA_KEY_PATH: /ca-key
F7T_PUB_USER_KEY_PATH: /user-key.pub
# common
F7T_AUTH_HEADER_NAME: Authorization
F7T_AUTH_REQUIRED_SCOPE: firecrest
F7T_AUTH_ROLE: firecrest-sa
F7T_AUTH_TOKEN_AUD: ""
F7T_CERTIFICATOR_HOST: svc-certificator
F7T_COMPUTE_HOST: svc-compute
F7T_FILESYSTEMS: "{
                   'cluster': [{'name':'HOME', 'path':'/home', 'description':'Users home filesystem'} , 
                               {'name':'SCRATCH', 'path':'/scratch', 'description':'Scratch filesystem'}] 
                 } "
F7T_GUNICORN_SSL: --ciphers TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256,TLS_AES_128_GCM_SHA256,DHE-RSA-AES256-GCM-SHA384,ECDHE-RSA-AES256-GCM-SHA384,ECDHE-RSA-AES128-GCM-SHA256 --ssl-version TLSv1_2 --keyfile /f7t-ssl.key --certfile /f7t-ssl.crt
F7T_JAEGER_AGENT: svc-jaeger
F7T_BASE_URL: http://svc-kong:8000
F7T_OBJECT_STORAGE: s3v4
F7T_RESERVATIONS_HOST: svc-reservations
F7T_SSH_CERTIFICATE_WRAPPER_ENABLED: True
F7T_SSL_ENABLED: "True"
F7T_SSL_CRT: /f7t-ssl.crt
F7T_SSL_KEY: /f7t-ssl.key
F7T_STATUS_HOST: svc-status
F7T_STORAGE_MAX_FILE_SIZE: 512000
F7T_STORAGE_HOST: svc-storage
F7T_SYSTEMS_INTERNAL_ADDR: 'svc-cluster:22'
F7T_SYSTEMS_INTERNAL_STATUS_ADDR: 'svc-cluster:22'
F7T_SYSTEMS_INTERNAL_COMPUTE_ADDR: 'svc-cluster:22'
F7T_SYSTEMS_INTERNAL_UTILITIES_ADDR: 'svc-cluster:22'
F7T_SYSTEMS_PUBLIC_NAME: 'cluster'
F7T_TASKS_HOST: svc-tasks
F7T_UTILITIES_MAX_FILE_SIZE: 5
F7T_UTILITIES_TIMEOUT: 5
F7T_UTILITIES_HOST: svc-utilities
# compute
F7T_COMPUTE_BASE_FS: "/home;/home"
F7T_COMPUTE_PORT: "5006"
F7T_SPANK_PLUGIN_OPTION: "--nohome"
F7T_SPANK_PLUGIN_ENABLED: "True"
# reservations
F7T_RESERVATIONS_PORT: "5005"
F7T_RESERVATIONS_TIMEOUT: 30
# status
F7T_STATUS_PORT: "5001"
F7T_STATUS_SERVICES: 'certificator;utilities;compute;tasks;storage;reservations'
# storage
F7T_CERT_CIPHER_KEY: Df6UZuoPoJ2u5yRwxNfFQ46Nwy8eW1OGTcuhlqn4ONo=
F7T_STORAGE_JOBS_MACHINE: "cluster"
F7T_STORAGE_PORT: "5002"
F7T_SYSTEMS_INTERNAL_STORAGE_ADDR: 'svc-cluster:22'
F7T_STORAGE_TEMPURL_EXP_TIME: "604800"
F7T_S3_SECRET_KEY: storage_secret_key
F7T_S3_ACCESS_KEY: storage_access_key
F7T_S3_PRIVATE_URL: "http://svc-minio.firecrest-dev:9000"
F7T_S3_PUBLIC_URL: "http://svc-minio.firecrest-dev:9000"
F7T_S3_REGION: "us-east-1"
F7T_S3_TENANT: null
F7T_STORAGE_POLLING_INTERVAL: 60
F7T_XFER_PARTITION: "xfer"
F7T_XFER_CONSTRAINT: ""
# tasks
F7T_TASKS_PORT: "5003"
F7T_PERSIST_HOST: localhost
F7T_PERSIST_PORT: "6379"
F7T_PERSIST_PWD: rediS2200
F7T_COMPUTE_TASK_EXP_TIME: "86400"
F7T_STORAGE_TASK_EXP_TIME: "2678400"
# utilities
F7T_UTILITIES_PORT: "5004"
# global
global:
  environment: "dev"
  include_reservations: True
  F7T_DEBUG_MODE: True
  F7T_GATEWAY_HOST: "svc-kong"
  F7T_GATEWAY_PORT: "8000"
  F7T_SWAGGER_HOST: "http://svc-openapi"
  F7T_SWAGGER_PORT: "8080"
  F7T_CERTIFICATOR_PORT: "5010"
  F7T_CERTIFICATOR_HOST: "svc-certificator"
  F7T_COMPUTE_PORT: "5006"
  F7T_COMPUTE_HOST: "svc-compute"
  F7T_STATUS_PORT: "5001"
  F7T_STATUS_HOST: "svc-status"
  F7T_STORAGE_PORT: "5002"
  F7T_STORAGE_HOST: "svc-storage"
  F7T_TASKS_PORT: "5003"
  F7T_TASKS_HOST: "svc-tasks"
  F7T_UTILITIES_PORT: "5004"
  F7T_UTILITIES_HOST: "svc-utilities"
  F7T_RESERVATIONS_PORT: "5005"
  F7T_RESERVATIONS_HOST: "svc-reservations"
  auth:
    - username: kc-demo
      F7T_AUTH_ISSUER: "http://svc-keycloak:8080/auth/realms/kcrealm"
      F7T_AUTH_REALM_PUBKEY: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqB44q32bQp8LbyW6dQvgsjseXESkLT1g5LQKGb+P79AC+nOAtxhn8i/kmgc6zsQH8NlUtNJruLxlzdo2/OGmlDGYZH1x6VmAwvJPJ4er0xPUrvZ8YclxYQC16PY5LFiQRNBMRyQwP5Kne1O46FpmADFVWMfoabdnaqoXexxB56b25o8tE2ulRBgfpnrRgZAvf7kWjugRCNO06FV074FVMYHA1aBk0ICyaFCDM/Tb5oaDyGr5c/ZvdrRUrw8vaiYyMgaAnnJPL75cebGoHeMJaEyZalsHA+iuhRAfeAwpSClsmhVqnfH7a7hqrqumVRo27dydqmfVgpFjU5gbFcBZ5wIDAQAB'
      F7T_AUTH_REALM_TYPE: "RS256"