apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-kong
  namespace: {{ .Values.global.namespace }}
  {{ if ne .Values.global.environment "dev" }}
  annotations:
    configmap.reloader.stakater.com/reload: "f7t-kong,common-env-file"    
  {{ end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
        role: gateway
    spec:
      containers:
      - image: kong:2.8.4
        env:
        - name: KONG_DECLARATIVE_CONFIG
          value: /kong/kong.yaml
        - name: KONG_DATABASE
          value: "off"
        name: kong
        ports:
        - containerPort: {{ .Values.global.F7T_GATEWAY_PORT | atoi }}
        volumeMounts:
        - mountPath: /var/log
          name: logs-endpoint
        - mountPath: /kong
          name: kong-config
        startupProbe:
          tcpSocket:
            port: {{ .Values.global.F7T_GATEWAY_PORT | atoi }}
          initialDelaySeconds: 5
          failureThreshold: 1
      volumes:
      - emptyDir: {}
        name: logs-endpoint
      - name: kong-config
        configMap:
          name: f7t-kong