apiVersion: v1
kind: Service # this is basically a proxy configuration to route connections to pods
metadata:
  name: svc-status
spec:
  selector:
    app: status # will match pods with this label
  ports:
  - port: 5001 # the service listen on
    targetPort: 5001 # the pods listen on
