apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: deploy-minio
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: minio
    strategy: {}
    template:
      metadata:
        labels:
          app: minio
      spec:
        containers:
        - args:
          - minio
          - server
          - /data
          env:
          - name: MINIO_ACCESS_KEY
            value: storage_access_key
          - name: MINIO_SECRET_KEY
            value: storage_secret_key
          image: minio/minio
          name: minio-k8-ci
          ports:
          - containerPort: 9000
          resources: {}
        restartPolicy: Always
  status: {}
kind: List
metadata: {}
