apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: svc-minio
  spec:
    ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
    selector:
      app: minio
  status:
    loadBalancer: {}
kind: List
metadata: {}
