apiVersion: v1
kind: Service # this is basically a proxy configuration to route connections to pods
metadata:
  name: svc-compute
spec:
  selector:
    app: compute # will match pods with this label
  ports:
  - port: 5006 # the service listen on
    targetPort: 5006 # the pods listen on