apiVersion: v1
data:
  F7T_UTILITIES_PORT: "{{ .Values.F7T_UTILITIES_PORT }}"
kind: ConfigMap
metadata:
  name: utilities-env-file
  namespace: {{ .Values.global.namespace }}
  annotations:
    reloader.stakater.com/match: "true"
