apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-utilities
  namespace: {{ .Values.global.namespace }}
  {{ if ne .Values.global.environment "dev" }}
    configmap.reloader.stakater.com/reload: "utilities-env-file,common-env-file"    
  {{ end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: utilities
  template:
    metadata:
      labels:
        app: utilities
      annotations:
      {{ if .Values.global.F7T_LOG_KIBANA | default false }}
        co.elastic.logs/processors.decode_json_fields.fields.0: "message"
        co.elastic.logs/processors.decode_json_fields.target: ""
        co.elastic.logs/processors.decode_json_fields.overwrite_keys: "true"
        co.elastic.logs/processors.decode_json_fields.add_error_key: "true"
      {{ end }}
      generateName: firecrest.utilities-1-
    spec:
      containers:
      - image: "{{ .Values.global.registry }}/utilities:{{ .Values.global.tag }}"
        imagePullPolicy: Always
        name: utilities
        ports:
        - containerPort: {{ .Values.F7T_UTILITIES_PORT | default 5004 | atoi }}
        envFrom:
        - configMapRef:
            name: common-env-file
        - configMapRef:
            name: utilities-env-file
        volumeMounts:
        - mountPath: /var/log
          name: logs-endpoint
        - mountPath: /user-key
          subPath: user-key
          name: user-key-public
        - mountPath: /f7t-ssl.crt
          name: f7t-ssl-crt
          subPath: f7t-ssl.crt
        - mountPath: /f7t-ssl.key
          name: f7t-ssl-key
          subPath: f7t-ssl.key
        startupProbe:
          tcpSocket:
            port: {{ .Values.F7T_UTILITIES_PORT | default 5004 | atoi }}
          initialDelaySeconds: 5
          failureThreshold: 1
      volumes:
      - emptyDir: {}
        name: logs-endpoint
      - name: user-key-public
        configMap:
          name: f7t-user-ssh-keys
      - name: f7t-ssl-crt
        configMap:
          name: f7t-ssl-crt
      - name: f7t-ssl-key
        configMap:
          name: f7t-ssl-key
