apiVersion: v1
kind: Service # this is basically a proxy configuration to route connections to pods
metadata:
  name: svc-utilities
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: utilities # will match pods with this label
  ports:
  - port: {{ .Values.F7T_UTILITIES_PORT | default 5004 | atoi }} # the service listen on
    targetPort: {{ .Values.F7T_UTILITIES_PORT | default 5004 | atoi }} # the pods listen on
