apiVersion: v1
data:
  F7T_TASKS_PORT: "{{ .Values.F7T_TASKS_PORT }}"
  F7T_PERSIST_HOST: "{{ .Values.F7T_PERSIST_HOST }}"
  F7T_PERSIST_PORT: "{{ .Values.F7T_PERSIST_PORT }}"
  F7T_COMPUTE_TASK_EXP_TIME: "{{ .Values.F7T_COMPUTE_TASK_EXP_TIME | toString }}"
  F7T_STORAGE_TASK_EXP_TIME: "{{ .Values.F7T_STORAGE_TASK_EXP_TIME | toString }}"
kind: ConfigMap
metadata:
  name: tasks-env-file
  namespace: {{ .Values.global.namespace }}
  annotations:
    reloader.stakater.com/match: "true"
