apiVersion: v1
kind: Service # this is basically a proxy configuration to route connections to pods
metadata:
  name: svc-tasks
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: tasks # will match pods with this label
  ports:
  - name: "tasks"
    port: {{ .Values.F7T_TASKS_PORT | atoi }} # tasks port
    targetPort: {{ .Values.F7T_TASKS_PORT | atoi}}
