apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: svc-jaeger
    namespace: {{ .Values.global.namespace }}
  spec:
    ports:
    - name: "6831"
      port: 6831
      targetPort: 6831
      protocol: UDP
    - name: "16686"
      port: 16686
      targetPort: 16686
    - name: "9411"
      port: 9411
      targetPort: 9411
      protocol: TCP
    selector:
      app: jaeger
  status:
    loadBalancer: {}
kind: List
metadata: {}
