apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: deploy-keycloak
    namespace: {{ .Values.global.namespace }}
  spec:
    replicas: 1
    strategy: {}
    selector:
      matchLabels:
        app: keycloak
    template:
      metadata:
        labels:
          app: keycloak
      spec:
        containers:
        - image: quay.io/keycloak/keycloak:18.0.2
          env:
          - name: KC_DB
            value: dev-file
          - name: KC_REALM_DISPLAY_NAME
            value: kcrealm
          - name: KC_REALM_NAME
            value: kcrealm
          - name: KEYCLOAK_USER
            value: admin
          - name: KEYCLOAK_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: f7t-keycloak-secret
                key: KEYCLOAK_PASSWORD
          args: ["start-dev", "--http-relative-path", "/auth", "--import-realm"]
          name: f7t-keycloak
          ports:
          - containerPort: 8080
            hostIP: 127.0.0.1
          - containerPort: 9990
            hostIP: 127.0.0.1
          volumeMounts:
          - mountPath: /opt/keycloak/data/import/
            name: f7t-keycloak-volume
          resources: {}
          startupProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            failureThreshold: 3
        volumes:
        - name: f7t-keycloak-volume
          configMap:
            name: f7t-keycloak-configmap
kind: List
