apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: svc-keycloak
    namespace: {{ .Values.global.namespace }}
  spec:
    type: ClusterIP
    selector:
      app: keycloak
    ports:
    - name: kc-api
      port: 8080
      targetPort: 8080
    - name: kc-admin
      port: 9990
      targetPort: 9990
  status:
    loadBalancer: {}
kind: List
