apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-cluster
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: cluster
  template:
    metadata:
      labels:
        app: cluster
    spec:
      hostname: cluster
      containers:
      - name: f7t-cluster
        image: "{{ .Values.global.registry }}/cluster:{{ .Values.global.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 22
        startupProbe:
          tcpSocket:
            port: 22
          initialDelaySeconds: 10
          failureThreshold: 1
