apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: svc-cluster
    namespace: {{ .Values.global.namespace }}
  spec:
    type: ClusterIP
    selector:
      app: cluster
    ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
kind: List
