apiVersion: v1
data:
  F7T_COMPUTE_BASE_FS: "{{ .Values.F7T_COMPUTE_BASE_FS }}"
  F7T_COMPUTE_PORT: "{{ .Values.F7T_COMPUTE_PORT }}"
  F7T_SPANK_PLUGIN_OPTION: "{{ .Values.F7T_SPANK_PLUGIN_OPTION }}"
  F7T_USE_SPANK_PLUGIN: "{{ .Values.F7T_USE_SPANK_PLUGIN }}"
kind: ConfigMap
metadata:
  name: compute-env-file
  namespace: {{ .Values.global.namespace }}
  annotations:
    reloader.stakater.com/match: "true"
