apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-compute
  namespace: {{ .Values.global.namespace }}
  annotations:
  {{ if ne .Values.global.environment "dev" }}
    configmap.reloader.stakater.com/reload: "compute-env-file,common-env-file"    
  {{ end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compute
  template:
    metadata:
      annotations:
      {{ if .Values.global.F7T_LOG_KIBANA | default false }}
        co.elastic.logs/processors.0.decode_json_fields.fields.0: "message"
        co.elastic.logs/processors.0.decode_json_fields.target: ""
        co.elastic.logs/processors.0.decode_json_fields.overwrite_keys: "true"
        co.elastic.logs/processors.0.decode_json_fields.add_error_key: "true"
        co.elastic.logs/processors.1.add_fields.target: ""
        co.elastic.logs/processors.1.add_fields.type: "logs"
        co.elastic.logs/processors.1.add_fields.dataset: "pilatus-v1.firecrest"
        co.elastic.logs/processors.1.add_fields.namespace: "firecrest"
      {{ end }}
      labels:
        app: compute
    spec:
      containers:
      - image: "{{ .Values.global.registry }}/compute:{{ .Values.global.tag }}"
        imagePullPolicy: Always
        name: compute
        ports:
        - containerPort: {{ .Values.F7T_COMPUTE_PORT | default 5006 | atoi }}
        envFrom:
        - configMapRef:
            name: common-env-file
        - configMapRef:
            name: compute-env-file
        volumeMounts:
        - mountPath: /var/log
          name: logs-endpoint
        - mountPath: /user-key
          subPath: user-key
          name: user-key-public
        - mountPath: /f7t-ssl.crt
          name: f7t-ssl-crt
          subPath: f7t-ssl.crt
        - mountPath: /f7t-ssl.key
          name: f7t-ssl-key
          subPath: f7t-ssl.key
        startupProbe:
          tcpSocket:
            port: {{ .Values.F7T_COMPUTE_PORT | default 5006 | atoi }}
          initialDelaySeconds: 5
          failureThreshold: 1
      restartPolicy: Always
      volumes:
      - emptyDir: {}
        name: logs-endpoint
      - name: user-key-public
        configMap:
          name: f7t-user-ssh-keys
      - name: f7t-ssl-crt
        configMap:
          name: f7t-ssl-crt
      - name: f7t-ssl-key
        configMap:
          name: f7t-ssl-key
