apiVersion: v1
data:
  F7T_RESERVATIONS_PORT: "{{ .Values.F7T_RESERVATIONS_PORT }}"
  F7T_RESERVATIONS_TIMEOUT: "{{ .Values.F7T_RESERVATIONS_TIMEOUT }}"
kind: ConfigMap
metadata:
  name: reservations-env-file
  namespace: {{ .Values.global.namespace }}
