apiVersion: v1
data:
  F7T_RESERVATIONS_PORT: {{ .Values.F7T_RESERVATIONS_PORT | default "5005" | quote }}
  F7T_RESERVATIONS_TIMEOUT: {{ .Values.F7T_RESERVATIONS_TIMEOUT | default "30" | quote }}
kind: ConfigMap
metadata:
  name: reservations-env-file
  namespace: {{ .Values.global.namespace }}
