apiVersion: v1
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: cm-openapi
    namespace: {{ .Values.global.namespace }}
  data:
    firecrest-api.yaml: |-
{{ .Files.Get "files/firecrest-api.yaml" | nindent 6 }}

kind: List
