apiVersion: v1
kind: Service # this is basically a proxy configuration to route connections to pods
metadata:
  name: svc-reservations
spec:
  selector:
    app: reservations # will match pods with this label
  ports:
  - port: 5005 # the service listen on
    targetPort: 5005 # the pods listen on