version: '3'

services:
  certificator:
    build: 
      context: ../../
      dockerfile: deploy/docker/certificator/Dockerfile
    env_file:
      - ./environment/common.env
    network_mode: "host"
    volumes:
      - "./environment/keys/ca-key:/ca-key:ro"
      - "./environment/keys/user-key.pub:/user-key.pub:ro"
      - ./logs/firecrest:/var/log:delegated

  compute:
    build:
      context: ../../
      dockerfile: deploy/docker/compute/Dockerfile
    env_file:
      - ./environment/common.env
    network_mode: "host"
    volumes:
      - "./environment/keys/user-key:/user-key:ro"
      - ./logs/firecrest:/var/log:delegated

  status:
    build:
      context: ../../
      dockerfile: deploy/docker/status/Dockerfile
    env_file:
      - ./environment/common.env
    network_mode: "host"
    volumes:
      - ./logs/firecrest:/var/log:delegated

  storage:
    build:
      context: ../../
      dockerfile: deploy/docker/storage/Dockerfile
    env_file:
      - ./environment/common.env
      - ./environment/storage.env
    network_mode: "host"
    depends_on:
      - "tasks"
      - "minio"
    volumes:
      - "./environment/keys/user-key:/user-key:ro"
      # custom host file
      - "./environment/hosts:/etc/hosts:ro"
      - ./logs/firecrest:/var/log:delegated

  tasks:
    build: 
      context: ../../
      dockerfile: deploy/docker/tasks/Dockerfile
    env_file:
      - ./environment/common.env
    environment:
      - F7T_PERSIST_PORT=6379
      - F7T_PERSIST_PWD=rediS2200
      - F7T_DEBUG_MODE=True
      - F7T_COMPUTE_TASK_EXP_TIME=86400
      - F7T_STORAGE_TASK_EXP_TIME=2678400
    depends_on:
      - "taskpersistence"
    network_mode: "host"
    volumes: 
      - ./logs/firecrest:/var/log:delegated

  utilities:
    build: 
      context: ../../
      dockerfile: deploy/docker/utilities/Dockerfile
    env_file:
      - ./environment/common.env
    network_mode: "host"
    volumes:
      - "./environment/keys/user-key:/user-key:ro"
      - ./logs/firecrest:/var/log:delegated

  # auxiliary containers
  cluster:
    # runs on private network to avoid conflict with a local SSH server
    build: 
      context: ./
      dockerfile: ./cluster/Dockerfile
    hostname: cluster
    ports:
      - "2223:22"

  minio:
    # runs on private network so "cluster" can reach it
    container_name: minio_test_build
    image: minio/minio
    command: minio server /data
    environment:
      MINIO_ACCESS_KEY: storage_access_key
      MINIO_SECRET_KEY: storage_secret_key
    ports:
      - "9000:9000"
    
  taskpersistence:
    image: redis:5
    command: redis-server /redis.conf
    network_mode: "host"
    volumes:
      - ./taskpersistence/redis.conf:/redis.conf:ro
      - ./logs/firecrest:/var/log:delegated

  opa:
    image: openpolicyagent/opa:0.22.0
    command: run --server --log-level=debug --log-format=json-pretty  /opa-files/data.json /opa-files/policy.rego
    network_mode: "host"
    ports: 
      - "8181:8181"    
    volumes: 
      - ./opa:/opa-files

  openapi:
    # image: swaggerapi/swagger-ui:v3.22.0
    build:
      context: ../../
      dockerfile: ./deploy/docker/openapi/Dockerfile
    ports:
      - "9090:8080"
    environment:
      SWAGGER_JSON: /tmp/openapi.yaml