#!groovy

node {
    print """{
                \"commit_id\": \"${env.COMMIT_ID}\",
                \"build_tag\": \"${env.BUILD_TAG}\"
                }"""
    try {
        stage('Build firecrest images') {
            // Sync project from github repo
            ansibleTowerProjectSync(
                towerServer: 'awx-local',
                async: false,
                importTowerLogs: true,
                project: 'Pre-Prod Project',
                removeColor: false,
                throwExceptionWhenFail: true,
                verbose: false
            )

            // Run template for image building
            ansibleTower(
                towerServer: 'awx-local',
                templateType: 'job',
                jobTemplate: 'Pre-Prod Docker Build',
                towerLogLevel: 'full',
                inventory: 'docker_registry',
                removeColor: false,
                verbose: true,
                credential: 'docker_registry_credentials',
                extraVars: """
                build_tag: ${env.BUILD_TAG}
                commit_id: ${env.COMMIT_ID}
                """,
                async: false
            )
         }
      }
      catch (e) {
        currentBuild.result = 'FAILED'
        throw e
      }
      finally {
      }
}
