##
##  Copyright (c) 2019-2021, ETH Zurich. All rights reserved.
##
##  Please, refer to the LICENSE file in the root directory.
##  SPDX-License-Identifier: BSD-3-Clause
##


---
- name: Remove FirecREST containers
  gather_facts: No
  hosts: all
  vars:
    firecrest_dir: "/home/centos/firecrest"

  tasks:
    - name: Stop and remove containers
      docker_container:
        name: "{{ item }}"
        state: absent
      with_items:
        - taskpersistence
        - tasks
        - certificator
        - compute
        - reservations
        - status
        - storage
        - utilities
        - cluster
        - fckeycloak
        - kong
        - opa
        - minio

    - name: Delete network demo_firecrest-internal
      community.general.docker_network:
        name: demo_firecrest-internal
        state: absent
        force: yes

    - name: Delete network firecrest-internal
      community.general.docker_network:
        name: firecrest-internal
        state: absent
        force: yes
    
    - name: Delete network demo_default
      community.general.docker_network:
        name: demo_default
        state: absent
        force: yes

    - name: Delete FirecREST images
      docker_image:
        name: "{{ docker_registry_host }}/{{ item }}:{{ build_tag }}"
        state: absent
      with_items:
        - tasks
        - certificator
        - compute
        - reservations
        - status
        - storage
        - utilities
      

    - name: Clean firecrest deploy folder
      file:
        state: absent
        path: "{{ firecrest_dir }}/"