##
##  Copyright (c) 2019-2021, ETH Zurich. All rights reserved.
##
##  Please, refer to the LICENSE file in the root directory.
##  SPDX-License-Identifier: BSD-3-Clause
##
FROM swaggerapi/swagger-ui:v3.22.0

COPY doc/openapi/firecrest-developers-api.yaml /tmp/openapi.yaml