apiVersion: v1
data:
  F7T_OS_AUTH_URL: {{ .Values.F7T_OS_AUTH_URL | default "" | quote }}
  F7T_OS_IDENTITY_PROVIDER: {{ .Values.F7T_OS_IDENTITY_PROVIDER | default "" | quote }}
  F7T_OS_PROTOCOL: {{ .Values.F7T_OS_PROTOCOL | default "openid" | quote }}
  F7T_OS_PROJECT_ID: {{ .Values.F7T_OS_PROJECT_ID | default "" | quote }}
  F7T_OS_CLIENT_ID: {{ .Values.F7T_OS_CLIENT_ID | default "" | quote }}
  F7T_OS_CLIENT_SECRET: {{ .Values.F7T_OS_CLIENT_SECRET | default "" | quote }}
  F7T_OS_DISCOVERY_ENDPOINT: {{ .Values.F7T_OS_DISCOVERY_ENDPOINT | default "" | quote }}
  F7T_OS_KEYSTONE_AUTH: {{ .Values.F7T_OS_KEYSTONE_AUTH | default "" | quote }}
  F7T_STORAGE_JOBS_MACHINE: "{{ .Values.F7T_STORAGE_JOBS_MACHINE }}"
  F7T_STORAGE_POLLING_INTERVAL: {{ .Values.F7T_STORAGE_POLLING_INTERVAL | default "60" | quote }}
  F7T_STORAGE_PORT: {{ .Values.F7T_STORAGE_PORT | default "5002" | quote }}
  F7T_STORAGE_TEMPURL_EXP_TIME: {{ .Values.F7T_STORAGE_TEMPURL_EXP_TIME | default "604800" | quote }}
  F7T_S3_PRIVATE_URL: {{ if .Values.F7T_S3_PRIVATE_URL }}{{ .Values.F7T_S3_PRIVATE_URL | quote }}{{ else }} null {{ end }}
  F7T_S3_PUBLIC_URL: {{ if .Values.F7T_S3_PRIVATE_URL }}{{ .Values.F7T_S3_PRIVATE_URL | quote }}{{ else }} null {{ end }}
  F7T_S3_REGION: {{ .Values.F7T_S3_REGION | default "us-east-1" | quote }}
  F7T_S3_TENANT: {{ if .Values.F7T_S3_TENANT }}{{ .Values.F7T_S3_TENANT | quote }}{{ else }} null {{ end }}
  F7T_SWIFT_SECRET_KEY: {{ if .Values.F7T_SWIFT_SECRET_KEY }}{{ .Values.F7T_SWIFT_SECRET_KEY | quote }}{{ else }} null {{ end }}
  F7T_SWIFT_PRIVATE_URL: {{ if .Values.F7T_SWIFT_PRIVATE_URL }}{{ .Values.F7T_SWIFT_PRIVATE_URL | quote }}{{ else }} null {{ end }}
  F7T_SWIFT_PUBLIC_URL: {{ if .Values.F7T_SWIFT_PUBLIC_URL }}{{ .Values.F7T_SWIFT_PUBLIC_URL | quote }}{{ else }} null {{ end }}
  F7T_SWIFT_API_VERSION: {{ .Values.F7T_SWIFT_API_VERSION | default "v1" | quote }}
  F7T_SWIFT_USER: {{ .Values.F7T_SWIFT_USER | default "" | quote }}
  F7T_SWIFT_PASS: {{ .Values.F7T_SWIFT_PASS | default "" | quote }}
  F7T_XFER_CONSTRAINT: {{ .Values.F7T_XFER_CONSTRAINT | default "" | quote }}
  F7T_XFER_PARTITION: {{ .Values.F7T_XFER_PARTITION | default "" | quote }}
kind: ConfigMap
metadata:
  name: storage-env-file
  namespace: {{ .Values.global.namespace }}
  annotations:
    reloader.stakater.com/match: "true"
