apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-storage
  namespace: {{ .Values.global.namespace }}
  annotations:
  {{ if ne .Values.global.environment "dev" }}
    configmap.reloader.stakater.com/reload: "storage-env-file,common-env-file"
    secret.reloader.stakater.com/reload: "firecrest-common-secrets"
  {{ end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      annotations:
      {{ if .Values.global.F7T_LOG_KIBANA | default false }}
        co.elastic.logs/processors.decode_json_fields.fields.0: "message"
        co.elastic.logs/processors.decode_json_fields.target: ""
        co.elastic.logs/processors.decode_json_fields.overwrite_keys: "true"
        co.elastic.logs/processors.decode_json_fields.add_error_key: "true"
        co.elastic.logs/processors.add_fields.target: ""
        co.elastic.logs/processors.add_fields.fields.type: "logs"
        co.elastic.logs/processors.add_fields.fields.dataset: "pilatus-v1.firecrest"
        co.elastic.logs/processors.add_fields.fields.namespace: "firecrest"
      {{ end }}
      labels:
        app: storage
    spec:
      containers:
      - image: "{{ .Values.global.registry }}/storage:{{ .Values.global.tag }}"
        imagePullPolicy: Always
        name: storage
        ports:
        - containerPort: {{ .Values.F7T_STORAGE_PORT | default 5002 | atoi }}
        env:
          - name: F7T_CERT_CIPHER_KEY
            {{ if eq .Values.global.environment "dev" }}
            value: {{ .Values.F7T_CERT_CIPHER_KEY | default "" | quote }}
            {{ else }}
            valueFrom:
              secretKeyRef:
                name: firecrest-common-secrets
                key: F7T_CERT_CIPHER_KEY
            {{ end }}
          - name: F7T_S3_SECRET_KEY
            {{ if eq .Values.global.environment "dev" }}
            value: {{ .Values.F7T_S3_SECRET_KEY | default "" | quote }}
            {{ else }}
            valueFrom:
              secretKeyRef:
                name: firecrest-common-secrets
                key: F7T_S3_SECRET_KEY
            {{ end }}
          - name: F7T_S3_ACCESS_KEY
            {{ if eq .Values.global.environment "dev" }}
            value: {{ .Values.F7T_S3_ACCESS_KEY | default "" | quote }}
            {{ else }}
            valueFrom:
              secretKeyRef:
                name: firecrest-common-secrets
                key: F7T_S3_ACCESS_KEY
            {{ end }}
        envFrom:
        - configMapRef:
            name: common-env-file
        - configMapRef:
            name: storage-env-file
        volumeMounts:
        - mountPath: /var/log
          name: logs-endpoint
        - mountPath: /user-key
          subPath: user-key
          name: user-key-public
        - mountPath: /f7t-ssl.crt
          name: f7t-ssl-crt
          subPath: f7t-ssl.crt
        - mountPath: /f7t-ssl.key
          name: f7t-ssl-key
          subPath: f7t-ssl.key
        startupProbe:
          tcpSocket:
            port: {{ .Values.F7T_STORAGE_PORT | default 5002 | atoi }}
          initialDelaySeconds: 5
          failureThreshold: 1
      volumes:
      - emptyDir: {}
        name: logs-endpoint
      - name: user-key-public
        configMap:
          name: f7t-user-ssh-keys
      - name: f7t-ssl-crt
        configMap:
          name: f7t-ssl-crt
      - name: f7t-ssl-key
        configMap:
          name: f7t-ssl-key
