# https://docs.github.com/en/actions/using-workflows
name: Firecrest Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-test-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create release notes
        shell: bash
        run: |
          git clone --branch ${GITHUB_REF_NAME} --depth 1 --recursive --shallow-submodules https://github.com/eth-cscs/firecrest && cd firecrest
          python3 ./ci/create_release_notes.py
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: FirecREST release ${{ github.ref }}
          body_path: ./firecrest/RELEASE_NOTES.md
          draft: false
          prerelease: false
